[Eth]
NetworkId = 968
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 1000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63abcd2b9b1baa327f2dda0f873f197ccd186"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://5fbe2ee9ec1b77f5ed379c52ff2c80aaca4579481b95dba80aa46bd0ac1f206a06965d5b25b6003adc471f43faf8fbb2f195fbc483114c3ddd1fb532a7bb1c65@192.168.250.11:30301",
    "enode://e186cf395fb58990c0915b63bbf91ceecd3c1bdb5f4659d99a21d9d485bed7e907919848be25932817016014ff008b8a598a0afd827a8353df7430e02da21618@192.168.250.12:30302",
    "enode://8f620d361595bda6cfb45cae4a9cf3cdbe38082ac7c5772e9db68120ba65bb7edc0fd8ed85e322d07b52e3b597b2e78221737c187ea6c39bd1b80e0181cb31cb@192.168.250.13:30303",
    "enode://1754d42e496f7c121aa03edd1d0a47e6bd08a463594cdd90d7c8c0087c3959e4dcdee4f93840c9b1e3a399ce8928f626a90b0acb33b51a873f65adf7191fe455@192.168.250.14:30304",
    "enode://2a894864537d138befe791bf2bb05cd22740480cecc61a5f49b4d637201d107270b4bbbc51d59961119bd94af09b0f7965aa735de4e89f2659fc51fe840c89f8@192.168.250.15:30305",
    "enode://cfe33547a34c797712c544c4c6793ad10ccc8d2909ff7a95a6c2b3bb12c3a3bb4fc49b4006408da001bd5a6ae74c82e6df3601d6df40e4309721d837e071d695@192.168.250.16:30306",
    "enode://bf41cf2262b713fb275c88589b21b0db1c81d2f876dc2ae0e240699c3fc760c38ff1bdb4f5e42d0a091126d892da3d1eb90198e0a272e1bfa36edf25a560e9bb@192.168.250.17:30307"
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "debug"
FileRoot = ""
