[Eth]
NetworkId = 968
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 1000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63abcd2b9b1baa327f2dda0f873f197ccd186"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://1354ce4460bae4e6e41fde49a43899ba4950ba843335427a30bd5a7eadaa3790b1a2e2d2163f7a02c480078b3064e130b7f281b86b97940cabeff0bbdebb430d@172.22.0.11:30303"
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
