[Eth]
NetworkId = 968
SyncMode = "full"
NoPruning = false
NoPrefetch = false
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TriesInMemory = 128
TrieTimeout = 3600000000000
EnablePreimageRecording = false
EVNNodeIDsToAdd = []

[Eth.Miner]
GasCeil = 35000000
GasPrice = 1000000000
Recommit = 10000000000
MaxWaitProposalInSecs = 3

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil= "0"
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63aBCd2b9b1baa327f2Dda0f873F197ccd186"

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000
Lifetime = 10800000000000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = true
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8546
EnableEVNFeatures = true
EnableQuickBlockFetching = true

[Node.P2P]
MaxPeers = 50
BootstrapNodes = [
    "enode://bdbae7a221748657424650676c9a262a1bd27e124714aeed5b3b32cbffccb11cfdf664942a34ecd981f52216da6be9e0edbdb2eda967bf6d563b80474684228d@172.22.0.11:30303"
]
NoDiscovery = false
StaticNodes = []
TrustedNodes = []
EnableMsgEvents = false
EVNNodeIdsWhitelist = []
ProxyedValidatorAddresses = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""