[Eth]
NetworkId = 968
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 1000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63abcd2b9b1baa327f2dda0f873f197ccd186"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://89aca788e89373dd8bd15c9e6a8a3284710f748f96edea86e26456367014a804e32002ce64bf7ca8a0950977fb441c84560e70b77b592ba8140bdb8075bb7cca@192.168.250.11:30303",
    "enode://e98fc7112aa82decea57a9de6e844795bc0042737ab2745b6af73c507a07c8be7297e432730a0db7dc0e8a0850ce678b45cefc03a778b85e666d16b87cc5fb59@192.168.250.12:30303",
    "enode://4ff1d596e98c1a8cf91865b05b0b8dad0cbae34f93d3fa9e9f73c6f4a181351b73e21ce665250ba29a5dc546eacdee72372d133d45af92eb6b1f3ab62a1b8185@192.168.250.13:30303",
    "enode://dd61453a40dc6897b8527a977c82bb2ba0c8b00bcd313139690fa593f3c9c4b35473f68a2566da4acdca2a3c8237cf0a041eed47bf2cc82350e1f2e6862053d1@192.168.250.14:30303",
    "enode://7c39fa075e883c38485a4024fc97770d2eae7e216c37a47b88ec1f0cd5f316bf4d98ff0151e2ac298664232b69759f540dffab06a7bd5bd0679bdac9b8dacb9f@192.168.250.15:30303",
    "enode://55b085bf16877e9dadf9ff11f17e93f8a5547475af1f5f6f9467bc018a2dfab1e3b03cc1c6dea190914ee92f0f84b532e1cec725739c0afa6bc49a84ecf4fcaf@192.168.250.16:30303",
    "enode://36b0495cf9ebbd1587f2d8ff5dd2d5727e5d9c7e20ef40130dedc3b7600241f303f1a6f7b5af1061952808e0cb441cc21e256bab54aa61b296299e96deee2033@192.168.250.17:30303"
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
