[Eth]
NetworkId = 968
SyncMode = "full"
DisablePeerTxBroadcast = false
EVNNodeIDsToAdd = []
EVNNodeIDsToRemove = []
EthDiscoveryURLs = []
SnapDiscoveryURLs = []
BscDiscoveryURLs = []
NoPruning = false
NoPrefetch = false
DirectBroadcast = false
DisableSnapProtocol = false
RangeLimit = false
JournalFileEnabled = false
DatabaseCache = 512
DatabaseFreezer = ""
PruneAncientData = false
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 0
TriesInMemory = 128
TriesVerifyMode = "local"
Preimages = false
FilterLogCacheSize = 0
EnablePreimageRecording = false
VMTrace = ""
VMTraceJsonConfig = ""
RPCGasCap = 0
RPCEVMTimeout = 0
RPCTxFeeCap = 0e+00
BlobExtraReserve = 0

[Eth.Miner]
GasFloor = 0
GasCeil = 35000000
GasPrice = 1000000000
Recommit = 10000000000
VoteEnable = false
DisableVoteAttestation = false

[Eth.Miner.Mev]
Enabled = true
GreedyMergeTx = true
BuilderFeeCeil = "0"
SentryURL = ""
ValidatorCommission = 1000

[[Eth.Miner.Mev.Builders]]
Address = "0x04d63abcd2b9b1baa327f2dda0f873f197ccd186"
URL = ""

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
OverflowPoolSlots = 0
Lifetime = 10800000000000
ReannounceTime = 0

[Eth.BlobPool]
Datadir = ""
Datacap = 0
PriceBump = 0

[Eth.GPO]
Blocks = 0
Percentile = 0
MaxHeaderHistory = 0
MaxBlockHistory = 0

[Node]
DataDir = ""
InsecureUnlockAllowed = true
EnableEVNFeatures = true
EnableQuickBlockFetching = true
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "mev", "net", "web3", "txpool", "parlia", "debug"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = []

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = [
    "enode://8afa057880b5e9aaaac1e44ce20313c476252c6c3eb3d614bfe6b24a06163fa5f28d5bab22374e9ed48d2b49dad600bb00a041c64f7fe335079f425b31234994@192.168.250.11:30303",
    "enode://7b126b361cbb00f9d1147ac46331faa10ac88b7e655c67080cde8d3364ff56e302169d745a74c3916b0163a5caf11901b3746703d54f8a6fbc6e5ea56c905bba@192.168.250.12:30303",
    "enode://43a4e1a07de4a799f8c187e10054ea05d46f94ba867329667247c260e9dd6eab89423c0398d772e5fbb8cd2bae87dda4b79b5f7761003669a15022912a61a6a5@192.168.250.13:30303",
    "enode://e369abece534a65de3ca59b2b13b9c039c5497f616141e2b7a1f60273a3d05c0e5016eb9963b8b2aee796fcfa4a3bf8fbd3a59f8f87ddc780089abfe54001395@192.168.250.14:30303",
    "enode://bbea6106f2ed68c0fdc45d8114d84a44c093f214bf6d8f7971f01b6647a931707e96494f966cd9964d0c91a7a62d2a9f548fa42f9d5965bbb8b9ba74abcb1108@192.168.250.15:30303",
    "enode://eaa1fa37403c45962103b36db09c2984adf3e8687bb39c73920e5e339f54b1f59ab17d364d201b168056ef1d99b339f31ae24ae0994803cdfdb35307b768e6fb@192.168.250.16:30303",
    "enode://ad0fe87c9e028c67d077a801038cbc6c4c499d7e1aa49bb73670ef54f9b105068e755759c76e5def4b8f3e604b1c407bea36dbb3aee0048652b59fbe6df42db4@192.168.250.17:30303"
]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false
PeerFilterPatterns = []

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
ReadHeaderTimeout = 0
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[FakeBeacon]
Enable = false
Addr = ""
Port = 0

[Node.LogConfig]
FilePath = "clog.log"
TimeFormat = "01-02|15:04:05.000"
MaxBackups = 1000
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
